# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Science',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.NullBooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Haslemere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.NullBooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Whiskey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.NullBooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Blockchain',
        ),
    ]
