# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalblog',
            name='post_category',
            field=models.CharField(choices=[('GENERAL_PYTHON', 'General Python'), ('DJANGO', 'Django'), ('BLOCKCHAIN', 'Blockchain'), ('DATA_SCIENCE', 'Data Science'), ('ARTIFICIAL_INTELLIGENCE', 'AI'), ('RANDOM_THOUGHTS', 'Random Thoughts')], default='RANDOM_THOUGHTS', max_length=10),
        ),
    ]
