# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalblog', '0002_generalblog_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalblog',
            name='post_content',
            field=models.FileField(default=None, upload_to="static/blogfiles/(('GENERAL_PYTHON', 'General Python'), ('DJANGO', 'Django'), ('BLOCKCHAIN', 'Blockchain'), ('DATA_SCIENCE', 'Data Science'), ('ARTIFICIAL_INTELLIGENCE', 'AI'), ('RANDOM_THOUGHTS', 'Random Thoughts'))"),
        ),
    ]
