# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-01 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalblog', '0003_generalblog_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalblog',
            name='post_category',
            field=models.CharField(choices=[('GENERAL_PYTHON', 'General Python'), ('DJANGO', 'Django'), ('BLOCKCHAIN', 'Blockchain'), ('DATA_SCIENCE', 'Data Science'), ('ARTIFICIAL_INTELLIGENCE', 'AI'), ('RANDOM_THOUGHTS', 'Random Thoughts')], default='RANDOM_THOUGHTS', max_length=15),
        ),
        migrations.AlterField(
            model_name='generalblog',
            name='post_content',
            field=models.FileField(default=None, upload_to='static/blogfiles'),
        ),
    ]
